export module DbUtils;

import ThirdParty.Protobuf;
import ThirdParty.PbGen;
import ThirdParty.Libpqxx;
import StrUtils;
import std.compat;
import Logger;
import ECSW;

using namespace std::chrono;

// SQL statement constants
namespace SqlConst {
	inline constexpr std::string_view Begin = "(";
	inline constexpr std::string_view End = ")";
	inline constexpr std::string_view Semicolon = ";";
	inline constexpr std::string_view Comma = ",";
	inline constexpr std::string_view Space = " ";
	inline constexpr std::string_view Default = "DEFAULT";
	inline constexpr std::string_view Combo = " AND ";
	inline constexpr std::string_view Not = "NOT";
	inline constexpr std::string_view PrimaryKey = "PRIMARY KEY";
	inline constexpr std::string_view Null = "NULL";
	inline constexpr std::string_view NotNull = "NOT NULL";
	inline constexpr std::string_view IsNull = "IS NULL";
	inline constexpr std::string_view NotIsNull = "NOT IS NULL";
	inline constexpr std::string_view Where = " WHERE ";
	inline constexpr std::string_view SelectAll = "*";
	inline constexpr std::string_view Update = "UPDATE";
	inline constexpr std::string_view UpdateCond = "UPDATECOND";
	inline constexpr std::string_view Quote = "\"";
}

enum class EMSqlOpType : uint8_t
{
	None,
	CreateTable,
	Insert,
	Query,
	Update,
	Delete,
	UpdateTable,
};

[[nodiscard]] constexpr const char* GetOpTypeBySqlOpType(EMSqlOpType eType) noexcept
{
	switch (eType)
	{
		case EMSqlOpType::CreateTable: return "CREATE TABLE ";
		case EMSqlOpType::Insert: return "INSERT INTO ";
		case EMSqlOpType::Query: return "SELECT ";
		case EMSqlOpType::Update: return "UPDATE ";
		case EMSqlOpType::Delete: return "DELETE FROM ";
		case EMSqlOpType::UpdateTable: return "ALTER TABLE ";
		default: return "";
	}
}


inline constexpr std::string_view SqlTableColQuery = R"delim(SELECT
column_name
FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '{}';)delim";

[[nodiscard]] constexpr const char* GetDbTypeByProtoType(FieldDescriptor::CppType pbType) noexcept
{
	switch (pbType)
	{
		case FieldDescriptor::CPPTYPE_INT32: return "integer";
		case FieldDescriptor::CPPTYPE_UINT32: return "integer";
		case FieldDescriptor::CPPTYPE_INT64: return "bigint";
		case FieldDescriptor::CPPTYPE_UINT64: return "bigint";
		case FieldDescriptor::CPPTYPE_STRING: return "character varying";
		case FieldDescriptor::CPPTYPE_MESSAGE: return "bytea";
		default: return "";
	}
}

void DirectFieldNameByProtoType([[maybe_unused]] const FieldDescriptor* field, [[maybe_unused]] std::string& out) noexcept
{
	// if (field->options().HasExtension(e_datetime))
	// {
	// 	out = std::format("EXTRACT(EPOCH FROM {} at time zone 'UTC') as {}", out, out);
	// }
}

// init table
void InitFieldByProtoType(const FieldDescriptor* field, std::vector<std::string>& out, std::vector<std::string>& keys)
{
	const char* typeStr = GetDbTypeByProtoType(field->cpp_type());
	if (!typeStr || typeStr[0] == '\0')
	{
		throw std::invalid_argument("Please Check CppType");
	}

	out.emplace_back(typeStr);

	const FieldOptions& options = field->options();

	// Type First Modify !!!
	switch (field->cpp_type())
	{
		case FieldDescriptor::CPPTYPE_STRING:
		{
			if (int lenLimit = PbGen::GetNumberFieldOptions(options, e_len_limit))
			{
				out.back().append(std::format("({})", lenLimit));
			}
			break;
		}
		case FieldDescriptor::CPPTYPE_UINT32:
		case FieldDescriptor::CPPTYPE_UINT64:
		{
			if (int genIndex = PbGen::GetNumberFieldOptions(field->options(), e_autogen))
			{
				out.emplace_back(std::format("GENERATED BY DEFAULT AS IDENTITY (START WITH {})", genIndex));
			}

			out.emplace_back(std::format("CHECK (\"{0}\" > -1)", field->name()));
			break;
		}
		default:
			break;
	}

	if (field->is_repeated())
	{
		out.back() += "[]";
	}

	if (!field->is_optional())
	{
		out.emplace_back(SqlConst::NotNull);
	}

	if (const std::string& defaultStr = PbGen::GetStringFieldOptions(options, e_default); !defaultStr.empty())
	{
		out.emplace_back(std::format("{0} {1}", SqlConst::Default, defaultStr));
	}

	if (PbGen::GetNumberFieldOptions(options, e_primary_key))
	{
		keys.emplace_back(std::format("\"{}\"", field->name()));
	}

	if (PbGen::GetNumberFieldOptions(options, e_unique))
	{
		out.emplace_back("UNIQUE");
	}
}

// Helper to format repeated field values
template<typename T, typename Getter>
void FormatRepeatedField(const FieldDescriptor* field, const Reflection* reflection, Message& data, std::string& out, Getter getter)
{
	const int fieldSize = reflection->FieldSize(data, field);
	if (fieldSize == 0)
	{
		out = "'{ }'";
		return;
	}
	
	out.reserve(fieldSize * 8); // Pre-allocate space
	for (int i = 0; i < fieldSize; i++)
	{
		out += std::format("{},", getter(reflection, data, field, i));
	}
	out.pop_back();
	out = std::format("'{{ {} }}'", out);
}

// get field data
void GetFieldValueByProtoType(const FieldDescriptor* field, const Reflection* reflection, Message& data, std::string& out)
{
	out.clear();

	if (field->is_optional() && !reflection->HasField(data, field))
	{
		out = SqlConst::Null;
		return;
	}

	const bool isRepeat = field->is_repeated();
	const FieldOptions& options = field->options();

	switch (field->cpp_type())
	{
		case FieldDescriptor::CPPTYPE_INT32:
			if (isRepeat)
			{
				FormatRepeatedField<int32_t>(field, reflection, data, out,
					[](const Reflection* r, Message& d, const FieldDescriptor* f, int i) {
						return r->GetRepeatedInt32(d, f, i);
					});
			}
			else
			{
				out = std::to_string(reflection->GetInt32(data, field));
			}
			break;
		case FieldDescriptor::CPPTYPE_UINT32:
			if (isRepeat)
			{
				FormatRepeatedField<uint32_t>(field, reflection, data, out,
					[](const Reflection* r, Message& d, const FieldDescriptor* f, int i) {
						return r->GetRepeatedUInt32(d, f, i);
					});
			}
			else
			{
				out = std::to_string(reflection->GetUInt32(data, field));
			}
			break;
		case FieldDescriptor::CPPTYPE_INT64:
			if (isRepeat)
			{
				FormatRepeatedField<int64_t>(field, reflection, data, out,
					[](const Reflection* r, Message& d, const FieldDescriptor* f, int i) {
						return r->GetRepeatedInt64(d, f, i);
					});
			}
			else
			{
				out = std::to_string(reflection->GetInt64(data, field));
			}
			break;
		case FieldDescriptor::CPPTYPE_UINT64:
			if (isRepeat)
			{
				FormatRepeatedField<uint64_t>(field, reflection, data, out,
					[](const Reflection* r, Message& d, const FieldDescriptor* f, int i) {
						return r->GetRepeatedUInt64(d, f, i);
					});
			}
			else
			{
				out = std::to_string(reflection->GetUInt64(data, field));
			}
			break;
		case FieldDescriptor::CPPTYPE_STRING:
			if (isRepeat)
			{
				const int fieldSize = reflection->FieldSize(data, field);
				if (fieldSize == 0)
				{
					out = "'{ }'";
				}
				else
				{
					out.reserve(fieldSize * 16);
					for (int i = 0; i < fieldSize; i++)
					{
						out += std::format("'{}',", reflection->GetRepeatedString(data, field, i));
					}
					out.pop_back();
					out = std::format("'{{ {} }}'", out);
				}
			}
			else
			{
				out = std::format("'{}'", reflection->GetString(data, field));
			}
			break;
		case FieldDescriptor::CPPTYPE_MESSAGE:
			if (isRepeat)
			{
				throw std::invalid_argument("Please Regist InsertField::CppType");
			}
			else
			{
				const Message& msg = reflection->GetMessage(data, field);
				msg.SerializeToString(&out);
				BytesToHexString(out);
				out = std::format("E'\\\\x{}'", out);
			}
			break;
		default:
			throw std::invalid_argument("Please Regist InsertField::CppType");
	}

	// Check string length limit
	if (field->cpp_type() == FieldDescriptor::CPPTYPE_STRING)
	{
		if (int len_limit = PbGen::GetNumberFieldOptions(options, e_len_limit))
		{
			if (out.size() > static_cast<size_t>(len_limit))
			{
				throw std::invalid_argument(std::format("field {} lenth > {} limit !!!", field->name(), len_limit));
			}
		}
	}
}

//set field data
void SetFieldValueByProtoType(const FieldDescriptor* field, const Reflection* reflection, Message& data, pqxx::field value, [[maybe_unused]] bool isQueryAll)
{
	switch (field->cpp_type())
	{
		case FieldDescriptor::CPPTYPE_INT32:
			reflection->SetInt32(&data, field, value.as<int32_t>());
			break;
		case FieldDescriptor::CPPTYPE_UINT32:
			reflection->SetUInt32(&data, field, value.as<uint32_t>());
			break;
		case FieldDescriptor::CPPTYPE_INT64:
			reflection->SetInt64(&data, field, value.as<int64_t>());
			break;
		case FieldDescriptor::CPPTYPE_UINT64:
			reflection->SetUInt64(&data, field, value.as<uint64_t>());
			break;
		case FieldDescriptor::CPPTYPE_STRING:
			reflection->SetString(&data, field, value.as<std::string>());
			break;
		case FieldDescriptor::CPPTYPE_MESSAGE:
		{
			if (field->is_repeated())
			{
				throw std::invalid_argument("Please Regist SelectField::Type");
			}
			Message* msg = reflection->MutableMessage(&data, field);
			std::string msgData = value.as<std::string>();
			msgData = msgData.substr(2);
			HexStringToBytes(msgData);
			msg->ParseFromString(msgData);
			break;
		}
		default:
			throw std::invalid_argument("Please Regist SelectField::Type");
	}
}

// get default field data
void GetFieldDefaultValueByProtoType(const FieldDescriptor* field, std::string& out) noexcept
{
	out.clear();

	if (field->is_repeated())
	{
		out = "{}";
		return;
	}

	switch (field->cpp_type())
	{
		case FieldDescriptor::CPPTYPE_INT32:
		case FieldDescriptor::CPPTYPE_UINT32:
		case FieldDescriptor::CPPTYPE_INT64:
		case FieldDescriptor::CPPTYPE_UINT64:
			out = "0";
			break;
		case FieldDescriptor::CPPTYPE_STRING:
			out = "''";
			break;
		case FieldDescriptor::CPPTYPE_MESSAGE:
			out = "E'\\\\x'";
			break;
		default:
			// For unknown types, leave empty - caller should handle
			break;
	}
}

class IDbSqlHelper
{
public:
	virtual ~IDbSqlHelper() = default;

	[[nodiscard]] virtual bool IsExist() = 0;

	virtual IDbSqlHelper& CreateTable() = 0;

	virtual IDbSqlHelper& UpdateTable() = 0;

	[[nodiscard]] virtual bool Commit() = 0;

	[[nodiscard]] virtual const std::string& GetName() = 0;

	[[nodiscard]] virtual std::string GetTableSchemaMd5() = 0;
};

export template <class TMessage = Message>
class DbSqlHelper : public IDbSqlHelper
{

public:

	DbSqlHelper(pqxx::dbtransaction* work, World::Ptr world, TMessage* entity = nullptr) noexcept
		: pWork(work), pWorld(world), pEntity(entity)
	{
	}

	~DbSqlHelper() override
	{
		ReleaseResult();
	}

	// Non-copyable
	DbSqlHelper(const DbSqlHelper&) = delete;
	DbSqlHelper& operator=(const DbSqlHelper&) = delete;

	// Movable
	DbSqlHelper(DbSqlHelper&&) noexcept = default;
	DbSqlHelper& operator=(DbSqlHelper&&) noexcept = default;

	[[nodiscard]] const std::string& GetName() override { return pEntity->GetDescriptor()->name(); }

	[[nodiscard]] const std::vector<TMessage*>& Result() const noexcept { return mResult; }

	[[nodiscard]] uint32_t ResultCount() const noexcept { return iQueryCount; }

	[[nodiscard]] bool Commit() override
	{
		BuildSqlStatement();

		if (!pWork || sSqlStatement.empty())
		{
			return false;
		}

		LoggerPrint::Log(pWorld, ELogLevel_Debug, "{}", sSqlStatement);
		try
		{
			pqxx::result result = pWork->exec(sSqlStatement);
			SetResult(result);
		}
		catch (const std::exception& e)
		{
			LoggerPrint::Log(pWorld, ELogLevel_Debug, "{}", e.what());
			bExecResult = false;
		}
		
		iLimitCount = 0;
		iExecResultCount = 0;
		eType = EMSqlOpType::None;
		mEles.clear();

		return bExecResult;
	}

	// create table
	DbSqlHelper<TMessage>& CreateTable() override
	{
		ChangeSqlType(EMSqlOpType::CreateTable);

		const Descriptor* descriptor = pEntity->GetDescriptor();

		std::vector<std::string> primaryKey;
		primaryKey.reserve(4);

		for (int i = 0; i < descriptor->field_count(); i++)
		{
			const FieldDescriptor* field = descriptor->field(i);

			// should init table
			if (field->is_repeated() && field->cpp_type() == FieldDescriptor::CPPTYPE_MESSAGE)
			{
				throw std::runtime_error("Not imp!!!");
			}

			std::vector<std::string> params;
			params.reserve(8);
			InitFieldByProtoType(field, params, primaryKey);

			// unregist type
			if (params.empty())
			{
				continue;
			}

			mEles.emplace(field->name(), std::vector<std::string>(params.begin(), params.end()));
		}

		if (mEles.contains(std::string(SqlConst::PrimaryKey)))
		{
			throw std::invalid_argument("Not Allow Exist 'PRIMARY KEY' map key!");
		}

		if (!primaryKey.empty())
		{
			std::string temp;
			temp.reserve(64);
			temp = SqlConst::Begin;
			for (size_t i = 0; i < primaryKey.size(); ++i)
			{
				temp += primaryKey[i];
				if (i + 1 < primaryKey.size())
				{
					temp += SqlConst::Comma;
				}
			}
			temp += SqlConst::End;

			std::vector<std::string> keyList;
			keyList.emplace_back(std::move(temp));

			mEles.emplace(std::string(SqlConst::PrimaryKey), std::move(keyList));
		}

		return *this;
	}

	DbSqlHelper<TMessage>& UpdateTable() override
	{
		ChangeSqlType(EMSqlOpType::UpdateTable);

		pqxx::result result = pWork->exec(vformat(SqlTableColQuery, make_format_args(GetName())));

		std::unordered_map<std::string, int> sqlColInfo;
		sqlColInfo.reserve(result.size());

		for (size_t row = 0; row < result.size(); row++)
		{
			sqlColInfo[result[row][0].as<std::string>()] = static_cast<int>(row);
		}

		const Descriptor* descriptor = pEntity->GetDescriptor();

		std::vector<std::string> primaryKey;
		primaryKey.reserve(4);
		std::string tempstr;
		tempstr.reserve(128);
		const char* opTypeStr = GetOpTypeBySqlOpType(eType);

		std::vector<std::string> history;
		history.reserve(descriptor->field_count() * 2);

		// check col
		for (int i = 0; i < descriptor->field_count(); i++)
		{
			const std::string& colName = descriptor->field(i)->name();
			std::vector<std::string> params;
			params.reserve(8);

			const FieldDescriptor* field = descriptor->field(i);

			// update col
			if (sqlColInfo.contains(colName))
			{
				InitFieldByProtoType(field, params, primaryKey);

				// can not null - remove NOT NULL from params
				if (!field->is_optional())
				{
					std::erase(params, std::string(SqlConst::NotNull));
				}

				// change type
				for (const std::string& param : params)
				{
					tempstr += param;
					tempstr += ' ';
				}

				history.emplace_back(std::format("{0}\"{1}\" ADD COLUMN \"new_{2}\" {3};\nUPDATE \"{1}\" SET \"new_{2}\" = \"{2}\";\n{0}\"{1}\" DROP COLUMN \"{2}\";\n{0}\"{1}\" RENAME COLUMN \"new_{2}\" TO \"{2}\";\n", opTypeStr, GetName(), colName, tempstr));

				if (!field->is_optional())
				{
					history.emplace_back(std::format("{0}\"{1}\" ALTER COLUMN \"{2}\" SET NOT NULL;\n", opTypeStr, GetName(), colName));
				}

				tempstr.clear();

				// already deal remove 
				sqlColInfo.erase(colName);
			}
			// create col
			else
			{
				InitFieldByProtoType(descriptor->field(i), params, primaryKey);
				for (const std::string& param : params)
				{
					tempstr += param;
					tempstr += ' ';
				}
				// ALTER TABLE tablename ADD COLUMN column_name data_type [column_constraint];
				history.emplace_back(std::format("{}\"{}\" ADD COLUMN \"{}\" {};\n", opTypeStr, GetName(), colName, tempstr));
				tempstr.clear();
			}
		}

		// remove col
		for (const auto& [colName, _] : sqlColInfo)
		{
			mEles[""].emplace_back(std::format("{}\"{}\" DROP COLUMN \"{}\";\n", opTypeStr, GetName(), colName));
		}

		// after change
		for (auto& item : history)
		{
			mEles[""].emplace_back(std::move(item));
		}

		return *this;
	}

	// insert
	DbSqlHelper<TMessage>& Insert(bool bSetDefault = false)
	{
		ChangeSqlType(EMSqlOpType::Insert);

		const Descriptor* descriptor = pEntity->GetDescriptor();
		const Reflection* reflection = pEntity->GetReflection();

		std::string value;

		std::string nowTime = std::to_string(time_point_cast<nanoseconds>(system_clock::now()).time_since_epoch().count());

		for (int i = 0; i < descriptor->field_count(); i++)
		{
			const FieldDescriptor* field = descriptor->field(i);

			const FieldOptions& options = field->options();

			// if primary_key and not other e. throw
			if (PbGen::GetNumberFieldOptions(options, e_primary_key) && !PbGen::GetNumberFieldOptions(options, e_autogen) && !reflection->HasField(*pEntity, field))
			{
				throw std::invalid_argument(std::format("Insert <{}> Data Not Set primary_key <{}> Data!", GetName(), field->name()));
			}

			value.clear();

			if (reflection->HasField(*pEntity, field))
			{
				GetFieldValueByProtoType(field, reflection, *pEntity, value);
			}

			if (!value.empty())
			{

			}
			// can not null
			else if (value.empty() && !field->is_optional())
			{
				if (const std::string& defaultStr = PbGen::GetStringFieldOptions(options, e_default); !defaultStr.empty())
				{
					value = defaultStr;
				}
				else if (bSetDefault)
				{
					if (PbGen::GetNumberFieldOptions(options, e_datetime))
					{
						value = nowTime;
					}
					else
					{
						GetFieldDefaultValueByProtoType(field, value);
					}
				}
				else
				{
					continue;
				}
			}
			else
			{
				continue;
			}


			mEles[field->name()].emplace_back(value);
		}

		return *this;
	}

	// query
	DbSqlHelper<TMessage>& SelectOne(const FieldDescriptor* field)
	{
		ChangeSqlType(EMSqlOpType::Query);

		if (mEles.contains(std::string(SqlConst::SelectAll)))
		{
			throw std::invalid_argument("exist other select statement!!");
		}

		std::string name = field->name();
		DirectFieldNameByProtoType(field, name);
		mEles[name];

		return *this;
	}

	template<auto EnumValue>
	DbSqlHelper<TMessage>& SelectOne()
	{
		const Descriptor* descriptor = pEntity->GetDescriptor();
		const FieldDescriptor* field = descriptor->FindFieldByNumber(EnumValue);
		if (!field)
		{
			return *this;
		}
		
		return SelectOne(field);
	}

	DbSqlHelper<TMessage>& SelectByKey(const FieldDescriptor* field)
	{
		ChangeSqlType(EMSqlOpType::Query);

		const FieldOptions& options = field->options();
		if (!PbGen::GetNumberFieldOptions(options, e_primary_key))
		{
			throw std::invalid_argument(std::format(" {} is not table {} key!", field->name(), GetName()));
		}

		std::string value;
		GetFieldValueByProtoType(field, pEntity->GetReflection(), *pEntity, value);

		if (value.empty())
		{
			throw std::invalid_argument(std::format(" table {} key is not set!", GetName()));
		}

		mEles[std::string(SqlConst::SelectAll)].emplace_back(std::format("\"{}\"={}", field->name(), value));

		return *this;
	}

	template<auto EnumValue>
	DbSqlHelper<TMessage>& SelectByKey()
	{
		const Descriptor* descriptor = pEntity->GetDescriptor();
		const FieldDescriptor* field = descriptor->FindFieldByNumber(EnumValue);
		if (!field)
		{
			return *this;
		}

		return SelectByKey(field);
	}

	DbSqlHelper<TMessage>& SelectAll(bool forEach = false, bool queryCount = false)
	{
		ChangeSqlType(EMSqlOpType::Query);

		// not default
		if (forEach)
		{
			const Descriptor* descriptor = pEntity->GetDescriptor();
			for (int i = 0; i < descriptor->field_count(); i++)
			{
				SelectOne(descriptor->field(i));
			}
			return *this;
		}

		// not default
		iQueryCount = queryCount;

		mEles[std::string(SqlConst::SelectAll)];

		if (mEles.size() > 1)
		{
			throw std::invalid_argument("exist other select statement!!");
		}

		return *this;
	}

	DbSqlHelper<TMessage>& SelectCond(const FieldDescriptor* field, const char* cond, const char* splicing)
	{
		const Reflection* reflection = pEntity->GetReflection();

		std::string value;
		GetFieldValueByProtoType(field, reflection, *pEntity, value);

		value = std::format("{}\"{}\"{}{}", splicing, field->name(), cond, value);

		const std::string selectAllKey(SqlConst::SelectAll);
		if (mEles.contains(selectAllKey))
		{
			mEles[selectAllKey].emplace_back(std::move(value));
		}
		else
		{
			mEles.begin()->second.emplace_back(std::move(value));
		}

		return *this;
	}

	template<auto EnumValue>
	DbSqlHelper<TMessage>& SelectCond(const char* cond, const char* splicing)
	{
		const Descriptor* descriptor = pEntity->GetDescriptor();
		const FieldDescriptor* field = descriptor->FindFieldByNumber(EnumValue);
		if (!field)
		{
			return *this;
		}

		return SelectCond(field, cond, splicing);
	}

	DbSqlHelper<TMessage>& UpdateOne(const FieldDescriptor* field)
	{
		ChangeSqlType(EMSqlOpType::Update);

		const Reflection* reflection = pEntity->GetReflection();

		std::string value;
		GetFieldValueByProtoType(field, reflection, *pEntity, value);

		mEles[std::string(SqlConst::Update)].emplace_back(std::format("\"{}\"={}", field->name(), value));

		return *this;
	}

	template<auto EnumValue>
	DbSqlHelper<TMessage>& UpdateOne()
	{
		const Descriptor* descriptor = pEntity->GetDescriptor();

		const FieldDescriptor* field = descriptor->FindFieldByNumber(EnumValue);
		if (!field)
		{
			return *this;
		}

		return UpdateOne(field);
	}

	DbSqlHelper<TMessage>& UpdateByKey(const FieldDescriptor* field)
	{
		ChangeSqlType(EMSqlOpType::Update);
		const Reflection* reflection = pEntity->GetReflection();
		const Descriptor* descriptor = pEntity->GetDescriptor();

		const FieldOptions& options = field->options();
		if (!PbGen::GetNumberFieldOptions(options, e_primary_key))
		{
			throw std::invalid_argument(std::format(" {} is not table {} key!", field->name(), GetName()));
		}

		std::string value;
		GetFieldValueByProtoType(field, reflection, *pEntity, value);

		if (value.empty())
		{
			throw std::invalid_argument(std::format(" table {} key is not set!", GetName()));
		}

		mEles[std::string(SqlConst::UpdateCond)].emplace_back(std::format("\"{}\"={}", field->name(), value));

		for (int i = 0; i < descriptor->field_count(); i++)
		{
			if (field != descriptor->field(i) && reflection->HasField(*pEntity, field))
			{
				UpdateOne(descriptor->field(i));
			}
		}

		if (mEles[std::string(SqlConst::Update)].empty())
		{
			throw std::invalid_argument(std::format(" table {} Not Update Data!", GetName()));
		}

		return *this;
	}

	template<auto EnumValue>
	DbSqlHelper<TMessage>& UpdateByKey()
	{
		const Descriptor* descriptor = pEntity->GetDescriptor();

		const FieldDescriptor* field = descriptor->FindFieldByNumber(EnumValue);
		if (!field)
		{
			return *this;
		}

		return UpdateByKey(field);
	}

	DbSqlHelper<TMessage>& UpdateByKey(int keyNumber)
	{
		const Descriptor* descriptor = pEntity->GetDescriptor();

		const FieldDescriptor* field = descriptor->FindFieldByNumber(keyNumber);
		if (!field)
		{
			return *this;
		}

		return UpdateByKey(field);
	}

	DbSqlHelper<TMessage>& UpdateCond(const FieldDescriptor* field, const char* cond, const char* splicing)
	{
		ChangeSqlType(EMSqlOpType::Update);

		const Reflection* reflection = pEntity->GetReflection();

		std::string value;
		GetFieldValueByProtoType(field, reflection, *pEntity, value);
		
		value = std::format("{}\"{}\"{}{}", splicing, field->name(), cond, value);

		mEles[std::string(SqlConst::UpdateCond)].emplace_back(std::move(value));

		return *this;
	}

	template<auto EnumValue>
	DbSqlHelper<TMessage>& UpdateCond(const char* cond, const char* splicing)
	{
		const Descriptor* descriptor = pEntity->GetDescriptor();

		const FieldDescriptor* field = descriptor->FindFieldByNumber(EnumValue);
		if (!field)
		{
			return *this;
		}

		return UpdateCond(field, cond, splicing);
	}

	DbSqlHelper<TMessage>& DeleteCond(const FieldDescriptor* field, const char* cond, const char* splicing)
	{
		ChangeSqlType(EMSqlOpType::Delete);

		const Reflection* reflection = pEntity->GetReflection();

		std::string value;

		GetFieldValueByProtoType(field, reflection, *pEntity, value);

		value = std::format("{}\"{}\"{}{}", splicing, field->name(), cond, value);

		mEles[std::string(SqlConst::UpdateCond)].emplace_back(std::move(value));

		return *this;
	}

	template<auto EnumValue>
	DbSqlHelper<TMessage>& DeleteCond(const char* cond, const char* splicing)
	{
		const Descriptor* descriptor = pEntity->GetDescriptor();

		const FieldDescriptor* field = descriptor->FindFieldByNumber(EnumValue);
		if (!field)
		{
			return *this;
		}

		return DeleteCond(field, cond, splicing);
	}

	[[nodiscard]] bool IsSuccess() noexcept
	{
		const bool success = bExecResult;
		bExecResult = false;
		return success;
	}

	[[nodiscard]] bool IsExist() override
	{
		return pWork->query_value<bool>(std::format("SELECT EXISTS ( SELECT 1 FROM pg_catalog.pg_tables WHERE schemaname = 'public' AND tablename = '{}');", GetName()));
	}

	DbSqlHelper<TMessage>& Limit(uint32_t limit)
	{
		if (iQueryCount)
		{
			throw std::invalid_argument("Exist Limit Cant use count(*)");
		}

		iLimitCount = limit;

		return *this;
	}

	[[nodiscard]] std::string GetBuildSqlStatement()
	{
		BuildSqlStatement();
		return sSqlStatement;
	}

	DbSqlHelper<TMessage>& InitEntity(TMessage& entity) noexcept
	{
		pEntity = &entity;
		return *this;
	}

	[[nodiscard]] std::string GetTableSchemaMd5() override
	{
		const Descriptor* descriptor = pEntity->GetDescriptor();

		std::string result;
		result.reserve(512);
		
		std::vector<std::string> out;
		out.reserve(8);
		std::vector<std::string> primaryKey;
		primaryKey.reserve(4);
		
		for (int i = 0; i < descriptor->field_count(); i++)
		{
			result += descriptor->field(i)->name();
			out.clear();
			InitFieldByProtoType(descriptor->field(i), out, primaryKey);
			for (const std::string& property : out)
			{
				result += property;
			}
		}

		for (const auto& key : primaryKey)
		{
			result += key;
		}

		return Md5Hash(result);
	}
private:

	bool ChangeSqlType(EMSqlOpType type)
	{
		if (eType != EMSqlOpType::None && eType != type)
		{
			throw std::invalid_argument("Not Commit to Change OpType");
		}

		eType = type;
		bExecResult = false;
		iExecResultCount = 0;
		return true;
	}

	void SetResult(pqxx::result& result)
	{
		switch (eType)
		{
			case EMSqlOpType::Query:
				bExecResult = true;
				if (!iQueryCount)
				{
					ParseQuery(result);
				}
				else
				{
					iQueryCount = result[0][0].as<uint32_t>();
				}
				break;
			case EMSqlOpType::Update:
			case EMSqlOpType::Delete:
			case EMSqlOpType::UpdateTable:
			case EMSqlOpType::CreateTable:
				bExecResult = true;
				break;
			case EMSqlOpType::Insert:
				bExecResult = (result.affected_rows() == iExecResultCount);
				break;
			default:
				throw std::invalid_argument("Please Imp SetResult Case!");
		}
	}

	void BuildSqlStatement()
	{
		if (eType == EMSqlOpType::None)
		{
			return;
		}

		std::string ss;
		ss.reserve(512);

		std::string limit;

		if (iLimitCount)
		{
			limit = std::format(" limit {}", iLimitCount);
		}

		switch (eType)
		{
			case EMSqlOpType::CreateTable:
			{
				ss += std::format("{} \"{}\"", GetOpTypeBySqlOpType(eType), GetName());

				if (mEles.empty())
				{
					// data null
					return;
				}

				ss += SqlConst::Begin;

				const Descriptor* descriptor = pEntity->GetDescriptor();

				for (int i = 0; i < descriptor->field_count(); i++)
				{
					const FieldDescriptor* field = descriptor->field(i);
					const std::string& fieldName = field->name();
					if (!mEles.contains(fieldName))
					{
						continue;
					}

					ss += SqlConst::Quote;
					ss += fieldName;
					ss += SqlConst::Quote;
					for (const std::string& props : mEles[fieldName])
					{
						ss += SqlConst::Space;
						ss += props;
					}

					ss += SqlConst::Comma;

					mEles.erase(fieldName);
				}

				auto it = mEles.begin();
				const auto itEnd = mEles.end();
				for (; it != itEnd; ++it)
				{
					ss += it->first;
					for (const std::string& props : it->second)
					{
						ss += SqlConst::Space;
						ss += props;
					}

					if (std::next(it) != itEnd)
					{
						ss += SqlConst::Comma;
					}
					else
					{
						ss += SqlConst::End;
					}
				}
				ss += SqlConst::Semicolon;

				iExecResultCount = 1;
				break;
			}
			case EMSqlOpType::Insert:
			{
				ss += std::format("{} \"{}\"", GetOpTypeBySqlOpType(eType), GetName());

				if (mEles.empty())
				{
					// key null
					return;
				}

				const size_t dataLen = mEles.begin()->second.size();
				if (dataLen == 0)
				{
					// value null
					return;
				}

				ss += SqlConst::Begin;
				auto it = mEles.begin();
				const auto itEnd = mEles.end();
				std::vector<std::vector<std::string>> mapping;
				mapping.reserve(mEles.size());
				
				for (; it != itEnd; ++it)
				{
					ss += SqlConst::Quote;
					ss += it->first;
					ss += SqlConst::Quote;

					mapping.emplace_back(it->second.begin(), it->second.end());

					if (std::next(it) != itEnd)
					{
						ss += SqlConst::Comma;
					}
					else
					{
						ss += SqlConst::End;
					}
				}

				ss += "VALUES";

				const size_t mappingSize = mapping.size();
				for (size_t lst = 0; lst < dataLen; ++lst)
				{
					ss += SqlConst::Begin;
					for (size_t pos = 0; pos < mappingSize; ++pos)
					{
						ss += mapping[pos][lst];
						if (pos + 1 < mappingSize)
						{
							ss += SqlConst::Comma;
						}
					}
					ss += SqlConst::End;

					if (lst + 1 < dataLen)
					{
						ss += SqlConst::Comma;
					}

					++iExecResultCount;
				}
				ss += SqlConst::Semicolon;
				break;
			}
			case EMSqlOpType::Query:
			{
				std::string selectElems;
				selectElems.reserve(128);
				auto it = mEles.begin();
				const auto itEnd = mEles.end();
				for (; it != itEnd; ++it)
				{
					if (!iQueryCount)
					{
						selectElems.append(it->first);
						if (std::next(it) != itEnd)
						{
							selectElems += SqlConst::Comma;
						}
					}
					else
					{
						selectElems = "COUNT(*)";
						break;
					}
				}

				ss += std::format("{}{} FROM \"{}\"", GetOpTypeBySqlOpType(eType), selectElems, GetName());

				bool hasCondition = false;

				for (it = mEles.begin(); it != itEnd; ++it)
				{
					for (const std::string& cond : it->second)
					{
						if (!hasCondition)
						{
							hasCondition = true;
							ss += SqlConst::Where;
						}

						ss += cond;
					}
				}

				ss += limit;

				ss += SqlConst::Semicolon;
				break;
			}
			case EMSqlOpType::Update:
			{
				const std::string updateKey(SqlConst::Update);
				auto& updates = mEles[updateKey];
				if (updates.empty())
				{
					throw std::invalid_argument("NOT SET UPDATE PROPERTY !");
				}

				std::string selectElems;
				selectElems.reserve(128);
				auto it = updates.begin();
				const auto itEnd = updates.end();
				for (; it != itEnd; ++it)
				{
					selectElems.append(*it);

					if (std::next(it) != itEnd)
					{
						selectElems += SqlConst::Comma;
					}
				}

				ss += std::format("{}\"{}\" SET {}", GetOpTypeBySqlOpType(eType), GetName(), selectElems);

				auto& updateConds = mEles[std::string(SqlConst::UpdateCond)];

				bool hasCondition = false;

				for (auto condIt = updateConds.begin(); condIt != updateConds.end(); ++condIt)
				{
					if (!hasCondition)
					{
						hasCondition = true;
						ss += SqlConst::Where;
					}

					ss += *condIt;
				}

				ss += limit;

				ss += SqlConst::Semicolon;
				break;
			}
			case EMSqlOpType::Delete:
			{
				ss += std::format("{} \"{}\"", GetOpTypeBySqlOpType(eType), GetName());

				bool hasCondition = false;

				if (!mEles.empty())
				{
					auto it = mEles.begin();
					const auto itEnd = mEles.end();

					for (; it != itEnd; ++it)
					{
						for (const std::string& cond : it->second)
						{
							if (!hasCondition)
							{
								hasCondition = true;
								ss += SqlConst::Where;
							}

							ss += cond;
						}
					}
				}

				ss += limit;

				ss += SqlConst::Semicolon;
				break;
			}
			case EMSqlOpType::UpdateTable:
			{
				for (const auto& [key, items] : mEles)
				{
					for (const auto& statement : items)
					{
						ss += statement;
					}
				}
				break;
			}
			default:
				throw std::invalid_argument("Please Imp BuildSqlStatement Case!");
		}

		sSqlStatement = std::move(ss);
	}

	void ParseQuery(pqxx::result& result)
	{
		ReleaseResult();

		std::vector<std::string> keys;
		keys.reserve(result.columns());
		for (pqxx::row_size_type col = 0; col < result.columns(); ++col)
		{
			keys.emplace_back(result.column_name(col));
		}

		const Descriptor* descriptor = pEntity->GetDescriptor();
		const Reflection* reflection = pEntity->GetReflection();

		const bool isQueryAll = mEles.contains(std::string(SqlConst::SelectAll));

		mResult.reserve(result.size());
		for (size_t row = 0; row < result.size(); ++row)
		{
			TMessage* gen = pEntity->New();

			const pqxx::row& rowInfo = result[row];
			for (pqxx::row_size_type col = 0; col < rowInfo.size(); ++col)
			{
				if (rowInfo[col].is_null())
				{
					continue;
				}

				if (const FieldDescriptor* field = descriptor->FindFieldByName(keys[col]))
				{
					SetFieldValueByProtoType(field, reflection, *gen, rowInfo[col], isQueryAll);
				}
			}
			mResult.emplace_back(gen);
		}
	}

	void ReleaseResult() noexcept
	{
		for (auto* item : mResult)
		{
			delete item;
		}
		mResult.clear();
	}
private:

	std::vector<TMessage*> mResult;

	EMSqlOpType eType = EMSqlOpType::None;

	// create table, insert
	std::unordered_map<std::string, std::vector<std::string>> mEles;

	pqxx::dbtransaction* pWork = nullptr;

	std::string sSqlStatement;

	bool bExecResult = false;

	int iExecResultCount = 0;

	uint32_t iLimitCount = 0;

	uint32_t iQueryCount = 0;

	TMessage* pEntity = nullptr;

	World::Ptr pWorld = nullptr;
};
