[Common]
locale=zh_CN.UTF-8
;locale=
;zh_CN,en_US,
l10nLang=zh_CN
l10nDataPath=./Config/Data/l10ncodes.bytes
;Debug,Normal,Warning,Error
LoggerLevel=Debug

[ControlServer]
port=1270

[GlobalServer]
port=1213
byCtl=1
ctlIp=127.0.0.1
ctlPort=1270

[AuthServer]
port=1212
byCtl=1
ctlIp=127.0.0.1
ctlPort=1270
connection=host=localhost port=5432 user=postgres password=1270 sslmode=prefer connect_timeout=10
dbnames=Account

[GateServer]
byCtl=1
ctlIp=127.0.0.1
ctlPort=1213

[DatabaseServer]
byCtl=1
ctlIp=127.0.0.1
ctlPort=1213
connection=host=localhost port=5432 user=postgres password=1270 sslmode=prefer connect_timeout=10
dbnames=Account,Nightmare

[LogicServer]
byCtl=1
ctlIp=127.0.0.1
ctlPort=1213
;redis://[[username:]password@]host[:port][/db]
connection=tcp://127.0.0.1:6379/0?keep_alive=true&socket_timeout=1s&connect_timeout=1s
